### ISSUE TITLE
search is broken

### ISSUE THREAD

**Issue by makefu** [namboy94/xdcc-dl#1]
Hey, just wanted to report that the search for xdcc-dl is currently broken. Error says:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/cwxxbpfz2i2j34f3sgmd6vdl6wv98c2s-python3-3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/nix/store/cwxxbpfz2i2j34f3sgmd6vdl6wv98c2s-python3-3.6.4/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/nix/store/psfn0vz316qdgqk68v09m87hrijb7p8w-python3.6-xdcc-dl-2.1.0/lib/python3.6/site-packages/xdcc_dl/gui/XDCCDownloaderGui.py", line 128, in search_thread
    self.search_results = searcher.search(search_term)
  File "/nix/store/psfn0vz316qdgqk68v09m87hrijb7p8w-python3.6-xdcc-dl-2.1.0/lib/python3.6/site-packages/xdcc_dl/pack_searchers/PackSearcher.py", line 72, in search
    results += procedure(search_phrase)
  File "/nix/store/psfn0vz316qdgqk68v09m87hrijb7p8w-python3.6-xdcc-dl-2.1.0/lib/python3.6/site-packages/xdcc_dl/pack_searchers/procedures/namibsun.py", line 38, in find_namibsun_packs
    "http://irc.namibsun.net:8000").text, "html.parser"
  File "/nix/store/2sii333r0xqz1cwinq88rdalqw5smjdk-python3.6-requests-2.18.4/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/nix/store/2sii333r0xqz1cwinq88rdalqw5smjdk-python3.6-requests-2.18.4/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/nix/store/2sii333r0xqz1cwinq88rdalqw5smjdk-python3.6-requests-2.18.4/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/nix/store/2sii333r0xqz1cwinq88rdalqw5smjdk-python3.6-requests-2.18.4/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/nix/store/2sii333r0xqz1cwinq88rdalqw5smjdk-python3.6-requests-2.18.4/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

I checked and indeed `http://irc.namibsun.net:8000` seems to be down. `http://irc.namibsun.net` redirects to some german soccer betting website.

Explicitly setting search provider to `nibl` works however.

Thanks for your work on xdcc-dl!

**Comment by namboy94** [comment]
For some reason I'm only just seeing this now. The issue should be resolved by now as irc.namibsun.net is no longer an option for ```xdcc-search```.

Thanks for posting the issue.
