### ISSUE TITLE
I keep getting the DownloadIncomplete Exception

### ISSUE THREAD

**Issue by Abdulla060** [namboy94/xdcc-dl#6]
I was experimenting with this package but I can seem to make it work for example I tried to download some random pack from HorribleSubs using this code:
`from xdcc_dl.xdcc import download_packs
from xdcc_dl.pack_search import SearchEngines
from xdcc_dl.entities import XDCCPack, IrcServer

search_results = [XDCCPack(IrcServer("irc.rizon.net"), "Ginpachi-Sensei", 7877)]

print(download_packs(search_results))`

and I kept getting this error

`C:\Users\Abdulla060\PycharmProjects\XDCC\venv\Scripts\python.exe C:/Users/Abdulla060/PycharmProjects/XDCC/main.py
Traceback (most recent call last):
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\xdcc_dl\xdcc\XDCCClient.py", line 114, in download
    self.start()
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\irc\client.py", line 1196, in start
    self.reactor.process_forever()
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\irc\client.py", line 842, in process_forever
    consume(infinite_call(one))
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\more_itertools\recipes.py", line 137, in consume
    deque(iterator, maxlen=0)
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\jaraco\itertools.py", line 416, in <genexpr>
    return (f() for _ in itertools.repeat(None))
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\irc\client.py", line 823, in process_once
    self.process_data(in_)
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\irc\client.py", line 787, in process_data
    conn.process_data()
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\irc\client.py", line 1079, in process_data
    self.reactor._handle_event(self, event)
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\irc\client.py", line 919, in _handle_event
    result = handler.callback(connection, event)
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\irc\client.py", line 1153, in _dispatcher
    method(connection, event)
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\xdcc_dl\xdcc\XDCCClient.py", line 306, in on_dccmsg
    end="\r", back=Back.LIGHTYELLOW_EX, fore=Fore.BLACK)
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\xdcc_dl\logging\Logger.py", line 128, in print
    self.log(message, None, back, fore, end)
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\xdcc_dl\logging\Logger.py", line 63, in log
    rows, columns = check_output(['stty', 'size']).split()
  File "C:\Users\Abdulla060\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\Abdulla060\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Abdulla060\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Abdulla060\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Abdulla060/PycharmProjects/XDCC/main.py", line 10, in <module>
    print(download_packs(search_results))
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\xdcc_dl\xdcc\__init__.py", line 34, in download_packs
    client.download()
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\xdcc_dl\xdcc\XDCCClient.py", line 133, in download
    self._disconnect()
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\xdcc_dl\xdcc\XDCCClient.py", line 381, in _disconnect
    self.connection.reactor.disconnect_all()
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\irc\client.py", line 848, in disconnect_all
    conn.disconnect(message)
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\irc\client.py", line 1024, in disconnect
    Event("dcc_disconnect", self.peeraddress, "", [message]))
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\irc\client.py", line 919, in _handle_event
    result = handler.callback(connection, event)
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\irc\client.py", line 1153, in _dispatcher
    method(connection, event)
  File "C:\Users\Abdulla060\PycharmProjects\XDCC\venv\lib\site-packages\xdcc_dl\xdcc\XDCCClient.py", line 326, in on_dcc_disconnect
    raise DownloadIncomplete()
xdcc_dl.xdcc.exceptions.DownloadIncomplete

Process finished with exit code 1
`

**Comment by namboy94** [comment]
I'm not quite sure what's going wrong on your end to be honest. The code you provided works fine for me.

**Comment by namboy94** [comment]
Maybe try again with the newest version.

I see that you're using Windows, I usually develop on/for linux and it's possible that I've overlooked something that makes the program break on Windows.

**Comment by Abdulla060** [comment]
Thank you for replying to my issue. this exception was actually was by a presmession problem on my installation of Windows 10 (an update completely bricked my system and i noticed it too late). 

However, I have found a bug while trying to run my program as a background service on Linux. the bug is in "Logging.py" line:63 [link](https://github.com/namboy94/xdcc-dl/blob/00c80dfebd3bbc66697b42f2eeb02e52fe048ba4/xdcc_dl/logging/Logger.py#L63).
in the code you are using "stty size" to get the size of the terminal however if you try to run "xdcc-dl" as a part of another program in the background (without a terminal) "stty size" will return an empty string then the code will try to split() it and unpack it to "rows" and "columns" which will result in a "ValueError" exception to be raised. therefore I think you should add a default value for these two variables if an exception is raised or maybe an option for the user to completely ignore the output of "stty" and directly use some default values.

**Comment by namboy94** [comment]
I've fixed that issue with ```stty size```. If the ```stty size``` call fails, the program will use 80 as a default value.

I've also added a ```--silent``` option that disables all output.

Those changes are now in the master branch and should be available on pypi soon.
